# Generated by Django 5.1.4 on 2025-01-08 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gardens',
            fields=[
                ('gardenID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('private', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=50, null=True)),
                ('scientific_name', models.CharField(max_length=100)),
                ('year', models.IntegerField(null=True)),
                ('family', models.CharField(max_length=100, null=True)),
                ('genus', models.CharField(max_length=100, null=True)),
                ('genus_id', models.IntegerField(null=True)),
                ('native', models.JSONField(blank=True, null=True)),
                ('shape_and_orientation', models.CharField(blank=True, max_length=100, null=True)),
                ('edible', models.BooleanField(blank=True, null=True)),
                ('edible_parts', models.JSONField(blank=True, null=True)),
                ('duration', models.JSONField(blank=True, null=True)),
                ('observation', models.CharField(max_length=200)),
                ('vegetable', models.BooleanField(blank=True, null=True)),
                ('conspicuous_fruit', models.BooleanField(blank=True, null=True)),
                ('conspicuous_flower', models.BooleanField(blank=True, null=True)),
                ('flower_color', models.CharField(max_length=50, null=True)),
                ('leaf_color', models.JSONField(blank=True, null=True)),
                ('fruit_color', models.JSONField(blank=True, null=True)),
                ('fruit_shape', models.CharField(max_length=50, null=True)),
                ('seed_persistant', models.BooleanField(blank=True, null=True)),
                ('leaf_retention', models.BooleanField(blank=True, null=True)),
                ('leaf_texture', models.CharField(blank=True, max_length=50, null=True)),
                ('growth_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('max_height', models.IntegerField(blank=True, null=True)),
                ('avg_height', models.IntegerField(blank=True, null=True)),
                ('growth_months', models.JSONField(blank=True, null=True)),
                ('row_spacing', models.JSONField(blank=True, null=True)),
                ('spread', models.JSONField(blank=True, null=True)),
                ('toxicity', models.CharField(max_length=5, null=True)),
                ('soil_humidity', models.IntegerField(blank=True, null=True)),
                ('soil_texture', models.IntegerField(blank=True, null=True)),
                ('soil_nutriments', models.IntegerField(blank=True, null=True)),
                ('soil_salinity', models.IntegerField(blank=True, null=True)),
                ('ph_max', models.IntegerField(blank=True, null=True)),
                ('ph_min', models.IntegerField(blank=True, null=True)),
                ('sunlight', models.IntegerField(blank=True, null=True)),
                ('max_temp', models.IntegerField(blank=True, null=True)),
                ('min_temp', models.IntegerField(blank=True, null=True)),
                ('days_to_harvest', models.IntegerField(blank=True, null=True)),
                ('atmospheric_humidity', models.IntegerField(blank=True, null=True)),
                ('min_precipitation', models.JSONField(blank=True, null=True)),
                ('max_precipitation', models.JSONField(blank=True, null=True)),
                ('minimum_root_depth', models.JSONField(blank=True, null=True)),
                ('bloom_months', models.JSONField(blank=True, null=True)),
                ('fruit_months', models.JSONField(blank=True, null=True)),
                ('ligneous_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPlant',
            fields=[
                ('personalPlantID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('plantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='bloom.plant')),
            ],
        ),
    ]
