# Generated by Django 5.1.4 on 2025-02-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='minimum_root_depth',
            new_name='min_root_depth',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='conspicuous_flower',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='conspicuous_fruit',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='flower_color',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='fruit_color',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='fruit_shape',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='leaf_color',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='leaf_retention',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='leaf_texture',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='native',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='seed_persistant',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='shape_and_orientation',
        ),
        migrations.AddField(
            model_name='personalplant',
            name='sensor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
