# Generated by Django 5.1.4 on 2025-03-16 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0002_rename_minimum_root_depth_plant_min_root_depth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gardens',
            old_name='gardenID',
            new_name='garden_id',
        ),
        migrations.RenameField(
            model_name='personalplant',
            old_name='personalPlantID',
            new_name='personalPlant_id',
        ),
        migrations.RenameField(
            model_name='personalplant',
            old_name='plantID',
            new_name='plant_id',
        ),
    ]
