# Generated by Django 5.1.4 on 2025-03-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0003_rename_gardenid_gardens_garden_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalplant',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.AddField(
            model_name='personalplant',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
