# Generated by Django 5.1.4 on 2025-04-20 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0004_rename_plant_id_personalplant_plant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalplant',
            name='garden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personal_plants', to='bloom.gardens'),
            preserve_default=False,
        ),
    ]
