# Generated by Django 5.1.4 on 2025-04-29 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0005_personalplant_garden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalplant',
            name='user_id',
        ),
        migrations.AddField(
            model_name='gardens',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalplant',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personal_plants', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
