# Generated by Django 5.1.4 on 2025-04-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0006_remove_personalplant_user_id_gardens_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gardens',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='personalplant',
            old_name='userID',
            new_name='user',
        ),
    ]
