# Generated by Django 5.1.4 on 2025-04-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0007_rename_userid_gardens_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gardens',
            old_name='garden_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='personalplant',
            old_name='personalPlant_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='plant_id',
            new_name='id',
        ),
    ]
