# Generated by Django 5.1.4 on 2025-05-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0008_rename_garden_id_gardens_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalplant',
            name='status',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Thirsty', 'Thirsty')], max_length=20, null=True),
        ),
    ]
