# Generated by Django 5.1.4 on 2025-05-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0010_personalplant_auto_watering_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='atmospheric_humidity',
            new_name='atmospheric_moisture',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='soil_humidity',
            new_name='soil_moisture',
        ),
    ]
