# Generated by Django 5.1.4 on 2025-05-04 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0011_rename_atmospheric_humidity_plant_atmospheric_moisture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='atmospheric_moisture',
            new_name='atmospheric_humidity',
        ),
    ]
