# Generated by Django 5.1.4 on 2025-05-04 06:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0012_rename_atmospheric_moisture_plant_atmospheric_humidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalplant',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
