# Generated by Django 5.1.4 on 2025-05-04 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0013_personalplant_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('personal_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bloom.personalplant')),
            ],
        ),
        migrations.CreateModel(
            name='WateringHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_watered', models.DateTimeField(auto_now_add=True)),
                ('personal_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watering_history', to='bloom.personalplant')),
            ],
        ),
    ]
