# Generated by Django 5.1.4 on 2025-05-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0014_statushistory_wateringhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='edible_parts',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='ligneous_type',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='max_precipitation',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='min_precipitation',
        ),
    ]
