name: frontend

on:
  push:
    branches: [ main ]
    paths: [ "Bloom-Frontend/**", ".github/workflows/frontend.yml" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/bloom-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (frontend)
        uses: docker/build-push-action@v6
        with:
          context: ./Bloom-Frontend
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # build args for React:
          # build-args: |
          #   REACT_APP_API_BASE_URL=${{ env.REACT_APP_API_BASE_URL }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 (pull & restart nginx)
        if: ${{ secrets.EC2_HOST != '' && secrets.EC2_USER != '' && secrets.EC2_SSH_KEY != '' && secrets.GHCR_PAT != '' }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            set -e
            cd "${{ secrets.COMPOSE_DIR || '/opt/bloom' }}"
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${GITHUB_REPOSITORY_OWNER}" --password-stdin
            docker compose pull nginx
            docker compose up -d nginx
