# Build 
FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json* ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

COPY . .
RUN npm run build

# Runtime 
FROM nginx:1.27-alpine

# SPA-friendly nginx config with history API fallback
# so /route URLs work when directly requested
RUN <<'EOF' sh -c 'cat > /etc/nginx/conf.d/default.conf'
server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  # Serve static files, try index.html as fallback (SPA)
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Optional: cache static assets a bit
  location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
    expires 7d;
    access_log off;
    try_files $uri =404;
  }
}
EOF


COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
HEALTHCHECK --interval=30s --timeout=3s --retries=3 CMD wget -qO- http://localhost/ > /dev/null || exit 1
